runtime: nodejs12

env_variables:
  SOME_VAR: 'example'

handlers:
  - url: /(.*\.(svg|png|css))$
    static_files: public/\1
    upload: public/.*$

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
